name: DevOps / Actionlint

on:
  pull_request:
  push:
    branches: [main, master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  actionlint:
    timeout-minutes: 15
    uses: FelipeFuhr/ffreis-workflows-general/.github/workflows/general-actionlint.yml@main
    with:
      working-directory: .
