name: DevOps / PR Hygiene

on:
  pull_request:
    types: [opened, edited, synchronize, reopened, ready_for_review]
  pull_request_target:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  semantic-pr:
    if: github.event_name == 'pull_request'
    permissions:
      pull-requests: read
    uses: FelipeFuhr/ffreis-workflows-general/.github/workflows/general-semantic-pr.yml@0aa2f6932831848d438834938acefcd98bc05c42 # post-v1.6.0

  actionlint:
    if: github.event_name == 'pull_request'
    permissions:
      contents: read
    uses: FelipeFuhr/ffreis-workflows-general/.github/workflows/general-actionlint.yml@0aa2f6932831848d438834938acefcd98bc05c42 # post-v1.6.0
    with:
      working-directory: "."

  labeler:
    if: github.event_name == 'pull_request_target'
    permissions:
      contents: read
      pull-requests: write
      issues: write
    uses: FelipeFuhr/ffreis-workflows-general/.github/workflows/general-labeler.yml@0aa2f6932831848d438834938acefcd98bc05c42 # post-v1.6.0
    with:
      rules-json: |-
        [
          {"label":"ci","patterns":[".github/workflows/**",".github/actions/**"]},
          {"label":"docs","patterns":["**/*.md"]}
        ]
