name: DevOps / Grype FS

on:
  pull_request:
  push:
    branches: [main, master]

jobs:
  grype-fs:
    uses: FelipeFuhr/ffreis-workflows-general/.github/workflows/general-scan-grype-fs.yml@main
    with:
      scan-ref: .
      upload-sarif: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == false }}
