name: Scorecard supply-chain security

on:
  branch_protection_rule:
  schedule:
    - cron: "20 7 * * 2"
  push:
    branches: [main]

permissions:
  contents: read
  actions: read
  security-events: write
  id-token: write

jobs:
  scorecard:
    uses: FelipeFuhr/ffreis-workflows-general/.github/workflows/general-scorecard.yml@57c46cfaf3b815c97c58983ae2be73fb85573fb6
    with:
      upload-sarif: true
      publish-results: true

