name: DevOps / Scorecard

on:
  schedule:
    - cron: "0 3 * * 0"
  workflow_dispatch:
  push:
    branches: [main]
permissions:
  actions: read
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  scorecard:
    uses: FelipeFuhr/ffreis-workflows-general/.github/workflows/general-scorecard.yml@main
    with:
      upload-sarif: true
