name: Scorecard supply-chain security

on:
  branch_protection_rule:
  schedule:
    - cron: "20 7 * * 2"
  push:
    branches: [main]

permissions:
  contents: read
  actions: read
  security-events: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  scorecard:
    uses: FelipeFuhr/ffreis-workflows-general/.github/workflows/general-scorecard.yml@01e2b12e992621fecf074b8a202f66044196f3bf
    with:
      upload-sarif: true
      publish-results: true

