name: DevOps / Semantic PR

permissions: {}

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  semantic-pr:
    permissions:
      contents: read
    uses: ffreis-org/ffreis-workflows-general/.github/workflows/general-semantic-pr.yml@0aa2f6932831848d438834938acefcd98bc05c42 # post-v1.6.0
