name: DevOps / Semantic PR

permissions: {}

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  semantic-pr:
    permissions:
      pull-requests: read
    uses: FelipeFuhr/ffreis-workflows-general/.github/workflows/general-semantic-pr.yml@ce7169b36bd25b1c4c0c8077aa78ecde6d6ca7d5 # v1.6.0
