name: DevOps / ShellCheck

on:
  pull_request:
  push:
    branches: [main, master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  shellcheck:
    timeout-minutes: 15
    uses: FelipeFuhr/ffreis-workflows-general/.github/workflows/general-shellcheck.yml@main
    with:
      working-directory: .
